spring.application.name=Spring-AI-Audio-Models
spring.ai.openai.api-key=your-api-key
#when the audio file is more than 1MB by default the size is less < 1MB
#spring.servlet.multipart.max-file-size=5MB